# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: LoonSoft Inc.
email: mlooney@gmail.dot.com
description: > # this means to ignore newlines until "baseurl:"
  Blog about what's going on at LoonSoft Inc. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.loonsoft.com" # the base hostname & protocol for your site
github_username:  mlooney

# Build settings
markdown: kramdown
