/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const main: (a: number, b: number) => number;
export const __wbg_get_streamconfig_buffer_size: (a: number) => number;
export const __wbg_get_streamconfig_channels: (a: number) => number;
export const __wbg_get_streamconfig_sample_rate: (a: number) => number;
export const __wbg_set_streamconfig_buffer_size: (a: number, b: number) => void;
export const __wbg_set_streamconfig_channels: (a: number, b: number) => void;
export const __wbg_set_streamconfig_sample_rate: (a: number, b: number) => void;
export const __wbg_streamconfig_free: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h19cec605fc05ec76: (a: number, b: number, c: any) => [number, number];
export const wasm_bindgen__convert__closures_____invoke__h9d6a48d38211c3df: (a: number, b: number, c: any, d: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h6802b77333e645bf: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h15dfa7bcd1967b9c: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h15dfa7bcd1967b9c_4: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h15dfa7bcd1967b9c_5: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h15dfa7bcd1967b9c_6: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h15dfa7bcd1967b9c_7: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h15dfa7bcd1967b9c_8: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h15dfa7bcd1967b9c_9: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h15dfa7bcd1967b9c_10: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__hdd30bf1251bed4e3: (a: number, b: number, c: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h862899c422c7d1f2: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__hcc66d9bf4d38a5a3: (a: number, b: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_exn_store: (a: number) => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_destroy_closure: (a: number, b: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
